name: 'Benchmarks'
on:
    workflow_dispatch:

jobs:
    tpchgen:
        name: TPCH Generator
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Cache generator
              uses: actions/cache@v2
              id: cache-generator
              with:
                  path: ./submodules/tpch-dbgen/dbgen/dbgen
                  key: ${{ runner.os }}-tpch-dben

            - name: Build generator
              if: steps.cache-generator.outputs.cache-hit != 'true'
              uses: duckdb/duckdb-wasm-ci-env@v0.4
              with:
                  script: |-
                      make -C ./submodules/tpch-dbgen/dbgen/ dbgen

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: tpch-dbgen
                  path: |
                      ./submodules/tpch-dbgen/dbgen/dbgen
                  retention-days: 1

    dataprep:
        name: Dataprep
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Cache rust build
              uses: actions/cache@v2
              with:
                  path: |
                      ./.cargo
                      ./target
                  key: ${{ runner.os }}-dataprep-${{ hashFiles('./Cargo.lock') }}-${{ hashFiles('./tools/dataprep/src/*.rs') }}
                  restore-keys: |
                      ${{ runner.os }}-dataprep-

            - name: Build generator
              uses: duckdb/duckdb-wasm-ci-env@v0.4
              with:
                  script: |-
                      cargo build --manifest-path=./Cargo.toml --release -p dataprep

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: dataprep
                  path: |
                      ./target/release/dataprep
                  retention-days: 1

    duckdb_shell:
        name: DuckDB Shell
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Git submodule status
              run: |
                  git submodule status ./submodules/duckdb > git_submodule_status.txt

            - name: Cache ccache
              uses: actions/cache@v2
              with:
                  path: |
                      ./.ccache
                  key: ${{ runner.os }}-duckdb-${{ hashFiles('git_submodule_status.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-duckdb-

            - name: Build DuckDB shell
              uses: duckdb/duckdb-wasm-ci-env@v0.4
              with:
                  script: |-
                      ccache -z
                      ./scripts/build_duckdb_shell.sh
                      ccache -s

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: duckdb-shell
                  path: ./submodules/duckdb/build/Release/duckdb
                  retention-days: 1

    dummy_benchmark:
        name: Dummy Benchmark
        runs-on: ubuntu-latest
        needs:
            - dataprep
            - tpchgen
            - duckdb_shell
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: 'recursive'
                  fetch-depth: 0

            - uses: actions/download-artifact@v2
              with:
                  name: dataprep
                  path: ./target/release/

            - uses: actions/download-artifact@v2
              with:
                  name: tpch-dbgen
                  path: ./submodules/tpch-dbgen/dbgen/

            - uses: actions/download-artifact@v2
              with:
                  name: duckdb-shell
                  path: ./submodules/duckdb/build/Release/

            - name: Cache node_modules
              uses: actions/cache@v2
              with:
                  path: |
                      ./node_modules
                      ./packages/benchmarks/node_modules
                      ./packages/duckdb-wasm/node_modules
                      ./packages/duckdb-wasm-shell/node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Prepare repository
              uses: duckdb/duckdb-wasm-ci-env@v0.4
              with:
                  script: |-
                      yarn install --frozen-lockfile
                      ./scripts/generate_tpch_tbl.sh 0.01
                      ./scripts/generate_tpch_arrow.sh 0.01
                      ./scripts/generate_tpch_duckdb.sh 0.01
                      ./scripts/generate_tpch_sqlite.sh 0.01

            - name: Restore NPM release
              run: |
                  ./scripts/npm_restore.sh

            - name: Build @duckdb/benchmarks
              uses: duckdb/duckdb-wasm-ci-env@v0.4
              with:
                  script: |-
                      yarn workspace @duckdb/benchmarks build
