name: 'Cloud Runners'
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    clang_format:
        name: Clang-Format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Lint ./lib
              uses: duckdb/duckdb-wasm-ci-env@v0.1
              with:
                  script: |-
                      python3 ./scripts/run_clang_format.py \
                        --exclude ./lib/build \
                        --exclude ./lib/third_party \
                        -r ./lib/

    eslint:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - name: Cache node_modules
              uses: actions/cache@v2
              with:
                  path: |
                      ./node_modules
                      ./packages/benchmarks/node_modules
                      ./packages/duckdb-wasm/node_modules
                      ./packages/duckdb-wasm-shell/node_modules
                  key: ${{ runner.os }}-npm-${{ hashFiles('./yarn.lock') }}

            - uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Prepare repository
              uses: duckdb/duckdb-wasm-ci-env@v0.1
              with:
                  script: |-
                      yarn install --frozen-lockfile

            - name: Lint @duckdb/duckdb-wasm
              uses: duckdb/duckdb-wasm-ci-env@v0.1
              with:
                  script: |-
                      yarn workspace @duckdb/duckdb-wasm run lint
