name: 'Cloud Runners'
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    clang_format:
        name: Clang-Format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Lint ./lib
              uses: duckdb/duckdb-wasm-ci-env@v0.1
              with:
                  script: |-
                      python3 ./scripts/run_clang_format.py \
                        --exclude ./lib/build \
                        --exclude ./lib/third_party \
                        -r ./lib/

    eslint:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Cache node_modules
              uses: actions/cache@v2
              with:
                  path: |
                      ./node_modules
                      ./packages/benchmarks/node_modules
                      ./packages/duckdb-wasm/node_modules
                      ./packages/duckdb-wasm-shell/node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Prepare repository
              uses: duckdb/duckdb-wasm-ci-env@v0.1
              with:
                  script: |-
                      yarn install --frozen-lockfile --prefer-offline

            - name: Lint @duckdb/duckdb-wasm
              uses: duckdb/duckdb-wasm-ci-env@v0.1
              with:
                  script: |-
                      yarn workspace @duckdb/duckdb-wasm run lint

    linux_x86_debug:
        name: Linux / x86 / Debug
        runs-on: ubuntu-latest
        needs:
            - clang_format
            - eslint
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: 'recursive'

            - name: Cache ccache
              uses: actions/cache@v2
              with:
                  path: |
                      /github/workspace/.ccache
                  key: ${{ runner.os }}-ccache

            - name: Prepare repository
              uses: duckdb/duckdb-wasm-ci-env@v0.1
              with:
                  script: |-
                      mkdir -p ./lib/build/debug ./reports
                      ./scripts/generate_tpch_raw.sh 0.01
                      ./scripts/generate_uni.sh

            - name: Build
              uses: duckdb/duckdb-wasm-ci-env@v0.1
              with:
                  script: |-
                      cmake \
                          -S./lib/ \
                          -B./lib/build/debug \
                          -DCODE_COVERAGE=1 \
                          -DCMAKE_BUILD_TYPE=Debug \
                          -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                          -DCMAKE_C_COMPILER=clang \
                          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
                          -DCMAKE_CXX_COMPILER=clang++ \
                          -DCMAKE_BUILD_TYPE=Debug
                      ccache -s
                      make -C./lib/build/debug -j`nproc`
                      ccache -s

            - name: Test
              uses: duckdb/duckdb-wasm-ci-env@v0.1
              with:
                  script: |-
                      export LLVM_PROFILE_FILE=./reports/lib.profraw
                      ./lib/build/debug/tester \
                          --source_dir=./lib/ \
                          --gtest_output=xml:./reports/tests_lib_debug.xml

            - name: Code Coverage
              uses: duckdb/duckdb-wasm-ci-env@v0.1
              with:
                  script: |-
                      llvm-profdata merge \
                          -sparse ./reports/lib.profraw \
                          -o ./reports/lib.profdata
                      llvm-cov show ./lib/build/debug/tester \
                          --instr-profile ./reports/lib.profdata \
                          -ignore-filename-regex submodules \
                          > ./reports/coverage_lib.txt
